package icom.yh.wish.entity;


import java.util.Date;
import java.util.Random;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import icom.yh.wish.util.CodeMsg;

/**
 * TProduct generated by hbm2java
 */
@Entity
@Table(name = "tb_product", catalog = "shop")
public class TbProduct implements java.io.Serializable {

	private Integer FClsId;
	private String F_PRODUCT_ID;
	private String FProductName; 
	private String FProductDesc;
	private Double F_SHOW_PRICE;
	private Double FPrice; 
	private Double F_REAL_PRICE;
	private Integer F_Number;
	private Double F_Express;
	
	private Date FProductTime;
	private Integer FStatus;
	private Integer FIsSpecial;
	private Integer FDegree;
	private String F_PATH;
	
	private String F_PATH1;
	private String F_PATH2;
	private String F_PATH3;
	private String F_PATH4;
	private String F_PATH5;
	private String F_PATH6;
	private String F_PATH7;
	private String F_PATH8; 
	
	private String F_PARENT_SKU;
	private String F_BRAND;
	private String F_COLOR;
	private String F_SIZE;
	private String F_LABEL;
	private Integer F_SALE_NUM;
    
	private CodeMsg codeMsg = new CodeMsg();
	
	public TbProduct(WishData wishData) {
		this.setF_PARENT_SKU(wishData.getParentSKU());
		this.setFProductName(wishData.getName()); 
		this.setFProductDesc(wishData.getDesc());
		this.setF_SHOW_PRICE(Double.parseDouble(wishData.getMsrp())*7);
		this.setFPrice((Double.parseDouble(wishData.getPrice())+2)*7);
		this.setF_REAL_PRICE(Double.parseDouble(wishData.getPrice())*7);
		this.setF_Number(wishData.getStock());
		this.setF_Express(Double.parseDouble(wishData.getFreight())*7);
		this.setFStatus(1);
		this.setFIsSpecial(1);
		Random r = new Random(5);
		int rnum = r.nextInt(10);
		this.setFDegree(rnum);
		this.setF_PATH(codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"+wishData.getItemId()+"-main.jpg");
		//this.setF_PATH(wishData.getMainImgUrl().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_PATH1(wishData.getImgUrl1().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_PATH2(wishData.getImgUrl2().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_PATH3(wishData.getImgUrl3().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_PATH4(wishData.getImgUrl4().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_PATH5(wishData.getImgUrl5().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_PATH6(wishData.getImgUrl6().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_PATH7(wishData.getImgUrl7().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_PATH8(wishData.getImgUrl8().replace("https://contestimg.wish.com/api/webimage/", codeMsg.getProperty("jiujichinaImgHttp")+wishData.getItemId()+"/"));
		this.setF_BRAND(wishData.getBrand());
		this.setF_COLOR(wishData.getColor());
		this.setF_SIZE(wishData.getSize());
		this.setF_LABEL(wishData.getLabel());
		this.setF_SALE_NUM(wishData.getSaleNum());
		
	}

	public TbProduct(String FProductId) {
		this.F_PRODUCT_ID = FProductId;
	}
  
	@Id
	@GeneratedValue
	@Column(name = "F_PRODUCT_ID", unique = true, nullable = false, length = 44)
	public String getF_PRODUCT_ID() {
		return F_PRODUCT_ID;
	}

	public void setF_PRODUCT_ID(String f_PRODUCT_ID) {
		F_PRODUCT_ID = f_PRODUCT_ID;
	}

	@Column(name = "F_ProductName", length = 44)
	public String getFProductName() {
		return this.FProductName;
	}

	public void setFProductName(String FProductName) {
		this.FProductName = FProductName;
	}

	@Column(name = "F_ProductDesc", length = 200)
	public String getFProductDesc() {
		return this.FProductDesc;
	}

	public void setFProductDesc(String FProductDesc) {
		this.FProductDesc = FProductDesc;
	}


 
	@Column(name = "F_Price")
	public Double getFPrice() {
		return FPrice;
	}
 
	@Column(name = "F_ClsId")
	public Integer getFClsId() {
		return FClsId;
	}

	public void setFClsId(Integer fClsId) {
		FClsId = fClsId;
	}

	@Column(name = "F_ProductTime")
	public Date getFProductTime() {
		return FProductTime;
	}

	public void setFProductTime(Date fProductTime) {
		FProductTime = fProductTime;
	}

	@Column(name = "F_Status")
	public Integer getFStatus() {
		return FStatus;
	}

	public void setFStatus(Integer fStatus) {
		FStatus = fStatus;
	}

	@Column(name = "F_IsSpecial")
	public Integer getFIsSpecial() {
		return FIsSpecial;
	}

	public void setFIsSpecial(Integer fIsSpecial) {
		FIsSpecial = fIsSpecial;
	}

	@Column(name = "F_Degree")
	public Integer getFDegree() {
		return FDegree;
	}

	public void setFDegree(Integer fDegree) {
		FDegree = fDegree;
	} 

	public String getF_PATH() {
		return F_PATH;
	}

	public void setF_PATH(String f_PATH) {
		F_PATH = f_PATH;
	}

	public String getF_PATH1() {
		return F_PATH1;
	}

	public void setF_PATH1(String f_PATH1) {
		F_PATH1 = f_PATH1;
	}

	public String getF_PATH2() {
		return F_PATH2;
	}

	public void setF_PATH2(String f_PATH2) {
		F_PATH2 = f_PATH2;
	}

	public String getF_PATH3() {
		return F_PATH3;
	}

	public void setF_PATH3(String f_PATH3) {
		F_PATH3 = f_PATH3;
	}

	public String getF_PATH4() {
		return F_PATH4;
	}

	public void setF_PATH4(String f_PATH4) {
		F_PATH4 = f_PATH4;
	}

	public String getF_PATH5() {
		return F_PATH5;
	}

	public void setF_PATH5(String f_PATH5) {
		F_PATH5 = f_PATH5;
	}

	public String getF_PATH6() {
		return F_PATH6;
	}

	public void setF_PATH6(String f_PATH6) {
		F_PATH6 = f_PATH6;
	}

	public String getF_PATH7() {
		return F_PATH7;
	}

	public void setF_PATH7(String f_PATH7) {
		F_PATH7 = f_PATH7;
	}

	public String getF_PATH8() {
		return F_PATH8;
	}

	public void setF_PATH8(String f_PATH8) {
		F_PATH8 = f_PATH8;
	}
 

	public Double getF_SHOW_PRICE() {
		return F_SHOW_PRICE;
	}

	public void setF_SHOW_PRICE(Double f_SHOW_PRICE) {
		F_SHOW_PRICE = f_SHOW_PRICE;
	}

	public Double getF_REAL_PRICE() {
		return F_REAL_PRICE;
	}

	public void setF_REAL_PRICE(Double f_REAL_PRICE) {
		F_REAL_PRICE = f_REAL_PRICE;
	}

	public Double getF_Express() {
		return F_Express;
	}

	public void setF_Express(Double f_Express) {
		F_Express = f_Express;
	}

	public void setFPrice(Double fPrice) {
		FPrice = fPrice;
	}

	public Integer getF_Number() {
		return F_Number;
	}

	public void setF_Number(Integer f_Number) {
		F_Number = f_Number;
	}

	 

	public String getF_PARENT_SKU() {
		return F_PARENT_SKU;
	}

	public void setF_PARENT_SKU(String f_PARENT_SKU) {
		F_PARENT_SKU = f_PARENT_SKU;
	}

	public String getF_BRAND() {
		return F_BRAND;
	}

	public void setF_BRAND(String f_BRAND) {
		F_BRAND = f_BRAND;
	}

	public String getF_COLOR() {
		return F_COLOR;
	}

	public void setF_COLOR(String f_COLOR) {
		F_COLOR = f_COLOR;
	}

	public String getF_SIZE() {
		return F_SIZE;
	}

	public void setF_SIZE(String f_SIZE) {
		F_SIZE = f_SIZE;
	}

	public String getF_LABEL() {
		return F_LABEL;
	}

	public void setF_LABEL(String f_LABEL) {
		F_LABEL = f_LABEL;
	}

	public Integer getF_SALE_NUM() {
		return F_SALE_NUM;
	}

	public void setF_SALE_NUM(Integer f_SALE_NUM) {
		F_SALE_NUM = f_SALE_NUM;
	} 
	
	
	
	
}
